### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by xuhang57**
How about this license? Or please suggesting another license.

Thanks!

### CODE REVIEW

**Comment by knikolla** [comment]
GPL isn't really suited for content, use one of the Creative Commons licenses, for example https://creativecommons.org/licenses/by-sa/4.0/

**Comment by xuhang57** [comment]
@knikolla  True, I cannot find this license on GitHub license. Thanks for the link and i am going to copy it.

**Comment by xuhang57** [comment]
@knikolla changed! Thanks for reviewing

**Comment by naved001** [comment]
The license should be in a different file. Github guide [here](https://help.github.com/articles/adding-a-license-to-a-repository/) also creates a new `LICENSE` file (like you had done earlier)

**Comment by xuhang57** [comment]
@naved001 right, but this is for non-code Licence I believe, which Github doesn't support this type of the license in the `LICENSE` file. So I put it in the Readme and people can view the license from there.

**Comment by xuhang57** [comment]
naved would send another PR. close this now.

**Pull request closed without merging**
